In [2]:
import pyarrow 
import pyarrow.parquet
import pandas as pd
from openff.toolkit.topology import Molecule
from openff.units import unit
from qcportal import PortalClient
import numpy as np

In [3]:
df = pd.read_parquet("mlpepper_gas_grid_esp.parquet")

In [4]:
df

smiles  \
0      [H:1][N:2]1[c:13]2[c:6]([n:7][c:8]([c:10]([n:1...   
1      [H:13][N:10]1[C:1]2=[C:7]([N:6]=[C:5]([N:4]([C...   
2      [H:15][C:3]1([C:4](=[O:5])[O:6][C:1]2([C:2]1([...   
3      [H:12][C:1]1([C:3]2([C:2]1([C:6]([C:5]3([C:4]2...   
4      [H:12][N:3]1[C:2]2=[C:1]([C:7](=[O:8])[N:6]([C...   
...                                                  ...   
68961  [H:19][C:1](=[O:2])[C@:3]1([C@@:12]([C@:11]2([...   
68962  [H:18][C:1](=[O:2])[C@:3]1([C@@:11]([C@:10]2([...   
68963  [H:19][C:1](=[O:2])[C@@:3]1([C@:12]([C@@:11]2(...   
68964  [H:20][C:1](=[O:2])[C@@:3]1([C@:13]([C@:12]2([...   
68965  [H:20][C:1](=[O:2])[C@:3]1([C@@:13]([C@:12]2([...   

                                                  dipole  \
0      [-0.10443668750542656, -1.6074249780538565, 0....   
1      [-0.7978420259036838, 1.5360907017859695, 1.28...   
2      [0.651552567765264, -0.25790020051764007, -0.0...   
3      [2.1875477030310275, -1.5783080897426558, 0.99...   
4      [1.2849355203740784, -0.19645810792871465, 1.9...   
...                                                  ...   
68961  [1.951845808030896, -0.3798215568463661, -1.24...   
68962  [0.6972250486887788, 0.672780703874265, 0.4901...   
68963  [0.6318098360299587, -0.7298442347342018, 1.31...   
68964  [-1.8604528354490242, -1.2481450893558872, 0.1...   
68965  [0.24839326909250303, 0.12270355829050317, -0....   

                                            conformation  \
0      [-6.84675074, -6.21371877, -0.26550788, -7.233...   
1      [-0.20376959, -0.11846028, -1.65358243, -1.594...   
2      [-0.72823895, 0.86456124, 0.54561595, 1.444442...   
3      [-2.29634493, 3.00038828, -4.15338052, 0.29361...   
4      [0.47236998, 0.89507412, -1.35743606, 1.617258...   
...                                                  ...   
68961  [-1.88622213, 4.26534409, 1.86454276, -3.46442...   
68962  [0.10710768, 4.67605362, -0.72040059, 0.972234...   
68963  [-0.56797697, 4.92381137, 2.11057884, -2.21540...   
68964  [3.08763867, 4.23371221, -0.06784356, 4.915992...   
68965  [3.50350622, 3.74509883, 2.3524949, 5.1808215,...   

                                            mbis-charges  \
0      [0.41426315466497865, -0.5375487118516106, 0.4...   
1      [-0.25475549009070736, 0.7333391646557704, -0....   
2      [0.07083810718826124, 0.07819907655701837, -0....   
3      [-0.3001431418974019, -0.15122065835707366, -0...   
4      [-0.2133582303443103, 0.4795287343061267, -0.6...   
...                                                  ...   
68961  [0.3818296321537853, -0.46269863308481995, 0.1...   
68962  [0.3952871412410599, -0.4422149711921003, 0.15...   
68963  [0.3858537491555347, -0.44826165115955874, 0.1...   
68964  [0.40187240282586806, -0.48690908895545365, 0....   
68965  [0.37778554461427033, -0.4587838074715926, 0.1...   

                                            mbis-dipoles  \
0      [0.008487496468123603, -0.03516715277277092, 0...   
1      [-0.01082104270849831, -0.022758380523471382, ...   
2      [-0.0007787565894870841, 0.11910291993748019, ...   
3      [0.015309242982609893, -0.01863415122001896, 0...   
4      [0.03603131947842891, 0.08037272345358445, -0....   
...                                                  ...   
68961  [-0.04788848655326677, 0.0411024791167475, 0.0...   
68962  [0.03277786284917251, 0.00037268454431099864, ...   
68963  [-0.06459246449886517, 0.026480309341318203, -...   
68964  [0.06618389416430392, 0.05297109773940994, -0....   
68965  [0.06445757745265007, 0.03158660551178736, 0.0...   

                                        mbis-quadrupoles  \
0      [-0.24581804598793677, 0.002285037013415781, 0...   
1      [-4.561705847398228, 0.12667017759784882, -0.0...   
2      [-4.182949638005885, -0.016561164125391846, -0...   
3      [-4.7908398728999, 0.04984952308286174, -0.007...   
4      [-4.582447390736581, -0.08606223325089135, -0....   
...                                                  ...   
68961  [-3.67327148495774

In [8]:
len(df['esp'].iloc[0])

66

In [ ]:
chunks = [902, 700, 663, 1395, 1035, 1204, 1140, 648, 646, 544, 703, 1204, 741, 990, 1596, 624, 656, 640, 816, 656, 799, 1363, 585, 532, 630, 969, 512, 1080, 686, 816, 1196, 544, 858, 1302, 756, 810, 1150, 624, 748, 656, 645, 574, 912, 936, 954, 1026, 588, 817, 640, 836, 592, 1125, 688, 704, 658, 702, 595, 608, 644, 901, 864, 1081, 1056, 1080, 702, 336, 644, 608, 756, 720, 850, 736, 630, 774, 585, 935, 903, 832, 476, 960, 559, 880, 700, 875, 750, 666, 912, 792, 1250, 574, 555, 560, 1081, 574, 602, 644, 731, 481, 756, 390, 608, 675, 672, 560, 816, 752, 742, 410, 722, 902, 1378, 1311, 855, 720, 880, 1188, 663, 969, 551, 1134, 1020, 1161, 1140, 940, 900, 816, 476, 792, 555, 798, 980, 1040, 595, 1078, 1056, 990, 810, 968, 902, 968, 968, 946, 1008, 1032, 1035, 1104, 1104, 1219, 966, 1020, 900, 560, 665, 912, 1008, 627, 704, 950, 372, 817, 820, 1225, 950, 1175, 1150, 1683, 1782, 1650, 1248, 666, 1368, 860, 936, 1026, 969, 1140, 1007, 1026, 1026, 966, 1152, 980, 940, 900, 840, 880, 640, 752, 286, 1683, 1452, 1617, 714, 731, 799, 697, 680, 940, 760, 820, 700, 629, 1150, 1300, 1012, 888, 1537, 630, 600, 1092, 495, 1352, 1325, 836, 1161, 1260, 1148, 660, 1334, 900, 1134, 1144, 1008, 912, 1012, 855, 880, 990, 1125, 946, 1323, 1269, 1260, 969, 943, 989, 867, 1071, 968, 814, 1120, 720, 960, 1083, 765, 814, 903, 960, 882, 960, 777, 882, 816, 816, 646, 858, 920, 1060, 1014, 1224, 735, 920, 800, 1320, 912, 1060, 784, 748, 880, 1200, 840, 918, 630, 602, 944, 851, 918, 962, 1215, 1008, 1058, 1060, 945, 1058, 624, 800, 860, 1081, 1104, 902, 1007, 884, 738, 756, 798, 810, 697, 792, 836, 1081, 1152, 1058, 663, 1081, 1320, 760, 697, 861, 738, 756, 880, 1250, 736, 816, 816, 645, 1144, 748, 992, 510, 882, 833, 1275, 828, 1113, 969, 840, 924, 819, 980, 966, 1148, 882, 882, 1000, 984, 1025, 931, 962, 855, 720, 984, 836, 1029, 1144, 1080, 816, 560, 1378, 902, 1092, 940, 705, 765, 1333, 912, 1128, 912, 714, 817, 880, 945, 1104, 782, 1148, 828, 860, 624, 714, 931, 1000, 736, 704, 901, 1150, 684, 792, 918, 1326, 882, 740, 832, 760, 760, 1066, 705, 799, 1035, 1078, 615, 574, 1092, 816, 1428, 936, 893, 714, 1003, 1000, 1053, 1014, 1161, 792, 897, 874, 980, 688, 1080, 1000, 1007, 880, 720, 1536, 1218, 546, 624, 700, 720, 1056, 748, 833, 645, 714, 629, 560, 1350, 1000, 792, 756, 1150, 1224, 532, 1080, 774, 950, 1118, 1125, 1767, 1175, 756, 598, 774, 1170, 468, 943, 1125, 611, 820, 702, 1326, 600, 1075, 720, 840, 684, 684, 494, 665, 800, 660, 780, 903, 840, 765, 987, 684, 663, 462, 1161, 817, 780, 950, 585, 1012, 1104, 1188, 1128, 780, 740, 820, 860, 1440, 1250, 1274, 1034, 1104, 792, 1551, 1296, 1150, 704, 968, 987, 986, 1288, 1200, 820, 990, 1100, 748, 924, 1128, 1012, 1025, 946, 828, 688, 1058, 1296, 820, 1225, 912, 900, 1326, 893, 860, 880, 999, 882, 810, 1071, 936, 714, 1007, 760, 1012, 714, 1247, 990, 828, 703, 945, 880, 861, 702, 1058, 1050, 792, 924, 720, 1272, 760, 828, 760, 574, 1344, 702, 846, 690, 900, 900, 950, 688, 705, 903, 987, 1026, 595, 1248, 1200, 666, 414, 962, 702, 931, 903, 1113, 728, 1014, 1050, 1232, 966, 855, 918, 1225, 735, 1075, 697, 779, 900, 756, 1080, 1020, 897, 912, 1122, 646, 836, 1152, 1032, 675, 704, 848, 880, 984, 988, 765, 714, 864, 738, 960, 1128, 920, 1170, 1040, 1300, 752, 1122, 810, 1650, 861, 800, 640, 736, 1100, 1078, 990, 574, 1150, 1134, 1710, 960, 1125, 1242, 1296, 684, 1200, 1440, 1440, 1320, 1350, 1350, 903, 1404, 760, 1200, 912, 1058, 966, 1058, 903, 893, 1323, 969, 1350, 805, 1058, 1008, 1323, 1150, 684, 850, 722, 777, 1323, 1150, 1058, 646, 1215, 1032, 731, 888, 984, 324, 1150, 1081, 1150, 1265, 1479, 817, 646, 627, 779, 924, 798, 924, 882, 612, 630, 836, 798, 594, 648, 900, 1080, 1176, 1140, 1045, 1176, 980, 828, 912, 578, 1100, 874, 976, 800, 574, 784, 990, 740, 900, 980, 765, 825, 915, 1235, 448, 532, 1188, 767, 1220, 1170, 930, 1092, 1044, 1218, 812, 1081, 720, 850, 990, 938, 992, 672, 546, 976, 1300, 1404, 1430, 1078, 1350, 1325, 1300, 1196, 1288, 903, 1368, 1200, 880, 1104, 874, 1035, 1104, 1200, 1008, 595, 752, 1050, 736, 1122, 1222, 1008, 1000, 1100, 1196, 1380, 1326, 1175, 987, 1040, 1100, 1012, 1127, 1404, 1248, 1127, 1020, 1334, 1104, 1104, 1325, 1120, 1128, 1128, 1144, 1029, 920, 1568, 903, 1127, 1035, 1176, 1056, 893, 1029, 1107, 1512, 1150, 1176, 1176, 1232, 1410, 1440, 1650, 1410, 1320, 1176, 1080, 1032, 1152, 1272, 1320, 1296, 1224, 1392, 1188, 1296, 1134, 1323, 940, 1122, 860, 1242, 874, 990, 588, 1020, 966, 697, 1128, 1152, 1176, 1200, 1128, 1440, 1290, 1470, 1440, 1410, 1222, 1378, 1102, 1189, 456, 1029, 494, 840, 990, 774, 882, 768, 874, 756, 714, 848, 990, 735, 705, 833, 874, 672, 1104, 966, 960, 969, 882, 1500, 988, 1200, 1175, 1350, 968, 1196, 820, 1225, 1150, 1350, 768, 976, 768, 1170, 779, 672, 924, 728, 630, 451, 1035, 1081, 1060, 984, 960, 874, 816, 966, 735, 954, 1152, 1269, 1215, 1152, 1026, 800, 1012, 1035, 1176, 1334, 738, 817, 874, 893, 931, 902, 902, 902, 800, 615, 860, 1060, 940, 900, 1008, 782, 688, 612, 372, 672, 848, 799, 765, 912, 969, 636, 817, 855, 969, 742, 637, 1056, 1134, 810, 1078, 546, 697, 640, 688, 782, 1254, 774, 893, 980, 920, 966, 1100, 1220, 924, 848, 1012, 1632, 920, 741, 888, 777, 690, 880, 1248, 1064, 1155, 1008, 798, 882, 624, 595, 736, 836, 867, 1323, 1323, 1269, 1215, 1323, 782, 940, 1040, 738, 855, 570, 572, 703, 564, 1300, 1430, 1080, 1188, 1080, 969, 912, 1215, 864, 935, 752, 1071, 920, 812, 1620, 1064, 1025, 900, 1107, 512, 952, 544, 740, 546, 576, 940, 1064, 819, 1350, 1032, 585, 880, 720, 900, 1368, 1170, 880, 1200, 1064, 1058, 616, 851, 648, 1316, 1470, 429, 1470, 1140, 1410, 546, 728, 693, 777, 756, 1200, 966, 1242, 650, 616, 1056, 496, 820, 860, 800, 1056, 920, 940, 936, 1056, 1008, 1375, 1008, 700, 846, 672, 688, 780, 820, 608, 1066, 440, 611, 640, 720, 646, 646, 630, 989, 693, 860, 774, 936, 820, 861, 702, 925, 1175, 1225, 950, 798, 931, 1175, 836, 1176, 546, 752, 532, 372, 952, 935, 798, 492, 1026, 931, 1035, 1058, 760, 820, 828, 532, 1150, 972, 900, 435, 532, 792, 714, 940, 777, 760, 820, 820, 800, 820, 1170, 1118, 1300, 1066, 520, 980, 1000, 860, 960, 1000, 585, 880, 880, 902, 880, 703, 966, 665, 589, 665, 684, 684, 884, 540, 684, 418, 627, 645, 570, 570, 912, 364, 714, 640, 840, 779, 495, 924, 595, 1400, 476, 1274, 476, 476, 798, 736, 432, 407, 640, 540, 987, 987, 1488, 968, 1122, 968, 1034, 570, 924, 880, 512, 684, 1122, 920, 1377, 1032, 1323, 1378, 1430, 1300, 968, 1248, 765, 846, 585, 680, 700, 810, 663, 697, 940, 1080, 1248, 731, 1060, 832, 800, 645, 882, 1150, 700, 704, 918, 966, 1242, 858, 1325, 528, 800, 901, 689, 754, 1148, 780, 1122, 1060, 1020, 931, 595, 1210, 1225, 1275, 1125, 1225, 912, 826, 799, 888, 816, 816, 686, 784, 629, 525, 714, 860, 663, 629, 714, 663, 512, 600, 615, 855, 1044, 768, 686, 893, 598, 800, 893, 1012, 1080, 290, 612, 704, 574, 560, 817, 945, 748, 836, 510, 434, 630, 1485, 1350, 595, 512, 1035, 1081, 1296, 1581, 836, 1188, 1188, 1188, 1242, 1080, 1104, 1012, 1173, 1265, 756, 840, 1250, 936, 1519, 1320, 1290, 946, 1125, 989, 880, 1426, 1581, 1457, 1550, 1643, 1092, 1372, 924, 1034, 912, 1080, 960, 912, 1400, 1456, 297, 504, 360, 560, 990, 1254, 1056, 1122, 1210, 1170, 1140, 1290, 602, 1350, 966, 611, 588, 615, 675, 702, 462, 462, 784, 765, 240, 1320, 828, 782, 403, 703, 703, 722, 456, 420, 350, 546, 598, 299, 738, 780, 532, 882, 630, 1320, 1000, 1320, 1200, 1173, 1118, 1080, 348, 1152, 372, 629, 1296, 870, 280, 817, 624, 272, 799, 574, 570, 1232, 1250, 882, 989, 945, 1269, 924, 525, 1050, 945, 1113, 580, 1250, 1620, 832, 640, 1377, 882, 624, 1125, 616, 1092, 1050, 820, 1269, 1173, 1219, 608, 782, 748, 935, 1219, 750, 630, 578, 574, 1050, 924, 924, 748, 848, 828, 704, 884, 969, 860, 874, 924, 798, 722, 800, 360, 680, 1012, 456, 525, 629, 560, 752, 752, 954, 780, 666, 731, 860, 600, 585, 752, 960, 720, 629, 602, 616, 656, 792, 920, 765, 720, 800, 288, 611, 1035, 816, 564, 966, 600, 552, 799, 630, 663, 656, 540, 720, 903, 616, 490, 350, 320, 456, 1456, 820, 820, 444, 810, 968, 990, 903, 1071, 1219, 1357, 980, 585, 330, 570, 363, 814, 770, 720, 800, 705, 714, 1014, 874, 952, 640, 540, 675, 867, 880, 630, 920, 672, 520, 492, 432, 408, 372, 555, 882, 1071, 782, 462, 924, 989, 966, 880, 782, 798, 1080, 1225, 640, 798, 615, 494, 720, 1128, 810, 920, 765, 1274, 1200, 481, 752, 984, 1092, 1150, 1008, 900, 1196, 702, 1064, 1260, 490, 858, 945, 960, 1152, 1125, 1056, 960, 1560, 1224, 1058, 1056, 1150, 1188, 966, 1128, 495, 646, 468, 665, 882, 620, 578, 608, 611, 968, 825, 468, 352, 430, 1197, 924, 792, 552, 570, 731, 1078, 560, 522, 756, 693, 946, 940, 810, 432, 602, 420, 900, 900, 920, 820, 390, 1248, 1430, 1196, 1326, 1378, 741, 912, 1127, 1104, 1035, 1035, 943, 740, 700, 592, 363, 1032, 390, 442, 630, 612, 884, 646, 840, 1248, 520, 680, 465, 798, 748, 540, 688, 1150, 468, 574, 615, 756, 1100, 1000, 799, 1120, 1000, 1060, 520, 645, 363, 341, 756, 560, 364, 429, 490, 420, 722, 360, 559, 630, 468, 646, 850, 700, 407, 390, 814, 770, 704, 576, 814, 880, 740, 1029, 912, 817, 560, 420, 672, 392, 840, 250, 817, 903, 462, 968, 1034, 680, 592, 594, 600, 370, 434, 546, 494, 646, 782, 384, 392, 912, 490, 465, 748, 533, 441, 874, 912, 680, 481, 333, 440, 850, 850, 765, 867, 735, 833, 782, 782, 560, 640, 470, 390, 598, 645, 1026, 1044, 1098, 1080, 972, 1104, 1032, 693, 828, 1170, 1144, 902, 660, 640, 1200, 1032, 1426, 1008, 1596, 1034, 741, 920, 1012, 612, 1050, 945, 560, 722, 722, 760, 975, 1218, 1118, 759, 759, 798, 759, 756, 1170, 1428, 1305, 1600, 1144, 1218, 1363, 1372, 713, 1144, 1568, 882, 1128, 740, 1127, 966, 1012, 1364, 920, 858, 697, 1219, 630, 966, 882, 756, 765, 840, 1260, 1035, 1222, 1248, 1170, 798, 1170, 1150, 752, 288, 261, 576, 680, 518, 705, 1035, 1150, 966, 840, 840, 882, 276, 943, 507, 840, 1196, 602, 549, 495, 943, 1012, 300, 966, 816, 352, 490, 504, 374, 455, 528, 828, 338, 352, 261, 279, 656, 319, 576, 637, 588, 364, 476, 420, 946, 570, 800, 342, 342, 612, 798, 720, 451, 714, 697, 748, 920, 480, 539, 1144, 602, 525, 968, 874, 1080, 1125, 1250, 784, 1140, 1272, 1296, 1092, 1029, 1150, 1175, 1025, 1100, 1100, 1404, 1534, 1430, 1144, 1248, 940, 880, 722, 836, 988, 931, 1056, 1200, 570, 440, 396, 1104, 1032, 936, 1071, 1071, 1197, 1113, 1736, 705, 480, 760, 656, 546, 640, 440, 792, 1000, 1125, 1125, 1225, 1175, 416, 390, 1071, 1200, 1032, 1080, 1224, 1152, 1012, 1012, 943, 897, 989, 920, 546, 704, 629, 1058, 1127, 1242, 1104, 1081, 777, 1056, 1081, 468, 600, 396, 738, 738, 846, 756, 774, 374, 672, 1092, 1032, 1472, 1020, 903, 1100, 1242, 882, 480, 759, 1250, 1225, 663, 816, 260, 680, 384, 504, 720, 444, 1173, 1196, 1196, 1242, 1150, 306, 800, 432, 640, 456, 434, 363, 364, 559, 1248, 1032, 1056, 1248, 1248, 840, 462, 640, 867, 900, 720, 440, 555, 440, 736, 644, 1007, 689, 432, 833, 728, 720, 585, 756, 799, 588, 816, 867, 860, 528, 588, 833, 484, 752, 969, 690, 782, 517, 615, 752, 784, 816, 800, 396, 451, 1188, 1276, 1210, 1188, 1078, 784, 630, 972, 882, 846, 1008, 570, 990, 946, 924, 902, 546, 540, 855, 594, 429, 608, 544, 864, 900, 882, 882, 616, 836, 912, 574, 588, 480, 780, 860, 918, 672, 429, 656, 420, 384, 559, 290, 444, 882, 918, 828, 846, 918, 752, 918, 518, 390, 369, 600, 400, 477, 324, 855, 722, 760, 836, 585, 874, 616, 576, 1152, 390, 880, 720, 697, 882, 960, 1104, 1056, 1134, 559, 765, 688, 624, 574, 666, 704, 660, 616, 714, 714, 697, 810, 931, 820, 648, 630, 810, 880, 735, 494, 363, 555, 440, 624, 1375, 1175, 1125, 1275, 1250, 442, 480, 540, 564, 494, 570, 481, 704, 360, 442, 380, 560, 297, 279, 280, 430, 600, 612, 319, 897, 765, 1000, 507, 612, 560, 585, 594, 300, 288, 1092, 1066, 1260, 420, 320, 256, 470, 602, 660, 555, 396, 414, 333, 407, 861, 848, 288, 525, 494, 931, 767, 931, 987, 882, 1178, 390, 861, 855, 455, 517, 440, 216, 273, 180, 407, 288, 297, 297, 784, 752, 784, 658, 848, 832, 288, 304, 429, 1150, 1215, 627, 1000, 1224, 972, 1008, 696, 700, 1408, 1363, 368, 369, 561, 288, 350, 288, 528, 441, 396, 520, 714, 1326, 1456, 1456, 1350, 1012, 1232, 1300, 1161, 1470, 1000, 1104, 1272, 1305, 1248, 1056, 1080, 1248, 882, 1080, 966, 1032, 1081, 1175, 738, 1225, 828, 943, 1175, 779, 1064, 816, 1056, 1060, 1008, 880, 760, 779, 1035, 1488, 1152, 616, 858, 1122, 1122, 1032, 875, 465, 1254, 722, 882, 940, 779, 901, 476, 988, 702, 1485, 840, 544, 960, 984, 720, 799, 504, 860, 912, 1450, 697, 476, 861, 990, 532, 574, 624, 1034, 476, 1170, 627, 528, 540, 902, 1425, 1080, 1288, 1200, 1242, 920, 702, 1071, 697, 1100, 840, 1166, 1045, 920, 1104, 966, 630, 819, 1378, 925, 969, 960, 940, 987, 1034, 1078, 1176, 1060, 1100, 924, 1100, 663, 697, 1475, 920, 1134, 858, 1176, 748, 903, 1056, 799, 989, 1620, 782, 984, 1116, 684, 1152, 925, 960, 645, 987, 903, 798, 741, 1008, 1140, 1100, 1080, 595, 680, 897, 740, 680, 1260, 920, 1242, 1269, 1081, 1200, 1176, 1152, 1242, 1458, 840, 760, 1173, 1232, 900, 893, 1040, 1007, 1224, 1222, 1000, 1372, 1457, 1050, 1144, 1100, 984, 874, 988, 817, 798, 1029, 1012, 880, 1122, 1092, 924, 840, 924, 1025, 1150, 950, 897, 828, 544, 1056, 1100, 1550, 966, 672, 925, 836, 1152, 1127, 1475, 1060, 900, 1104, 1325, 1120, 1152, 1224, 1325, 1404, 1173, 1058, 861, 1056, 1300, 1568, 810, 1025, 816, 1300, 1316, 1590, 816, 1352, 1122, 1036, 1166, 1100, 1170, 1352, 1122, 1020, 966, 1488, 1215, 1029, 1534, 1392, 770, 945, 1188, 1080, 1275, 1568, 924, 1296, 966, 1320, 1056, 864, 1128, 1071, 1188, 1378, 1026, 902, 851, 1056, 1104, 1155, 1104, 816, 750, 1311, 867, 1080, 1012, 816, 720, 1512, 1540, 1596, 1428, 1372, 1014, 1334, 1035, 1012, 1215, 1029, 920, 1071, 884, 940, 800, 864, 1008, 585, 1419, 1040, 1350, 972, 1025, 1419, 1066, 1081, 966, 1496, 768, 1071, 1056, 900, 1127, 1034, 1368, 1000, 1000, 1248, 1056, 1428, 966, 1100, 875, 1375, 1175, 1025, 700, 1127, 966, 990, 833, 836, 448, 850, 703, 880, 646, 920, 1014, 969, 1560, 1260, 897, 736, 828, 672, 1395, 1204, 987, 880, 1012, 1008, 816, 1134, 1029, 1404, 1431, 612, 1224, 888, 1078, 984, 627, 612, 924, 912, 1060, 1050, 1104, 1152, 989, 1196, 1215, 882, 588, 792, 1071, 1350, 594, 1080, 792, 1100, 1118, 702, 966, 1176, 924, 697, 990, 902, 663, 1715, 1269, 966, 1204, 836, 2030, 1131, 1118, 1334, 1222, 1352, 748, 1288, 946, 1539, 1450, 1134, 700, 798, 1652, 1568, 1536, 1032, 860, 720, 1180, 1220, 1400, 1431, 774, 1170, 594, 496, 936, 1350, 880, 1050, 1150, 1100, 1274, 1400, 1056, 924, 720, 756, 984, 1008, 1200, 1012, 768, 945, 920, 966, 1100, 924, 592, 1219, 1050, 1092, 672, 1160, 1431, 1104, 1056, 660, 1175, 799, 585, 481, 658, 1008, 644, 752, 900, 820, 760, 672, 840, 731, 720, 741, 760, 946, 980, 816, 1128, 1008, 1128, 738, 882, 888, 817, 805, 714, 858, 880, 1078, 946, 903, 1225, 1000, 990, 1272, 1410, 777, 840, 703, 532, 627, 594, 1144, 1056, 1050, 800, 816, 1210, 1248, 1248, 1025, 760, 836, 592, 1643, 1260, 1008, 1650, 1050, 1075, 512, 1260, 975, 1768, 988, 1170, 1000, 902, 875, 1230, 1380, 1470, 960, 1242, 940, 615, 960, 680, 1118, 846, 810, 559, 1215, 779, 1029, 555, 966, 860, 987, 792, 1000, 975, 589, 940, 893, 462, 1092, 903, 817, 672, 697, 688, 663, 720, 1032, 1127, 903, 520, 1007, 1296, 912, 1058, 1050, 1012, 1372, 680, 946, 901, 966, 756, 656, 765, 966, 828, 720, 1265, 950, 936, 1176, 924, 816, 1218, 1248, 836, 960, 714, 900, 980, 1080, 918, 510, 782, 1075, 1175, 1215, 924, 760, 1078, 1125, 1344, 820, 1378, 1323, 1325, 902, 1050, 1100, 1612, 924, 940, 987, 924, 943, 1008, 1128, 518, 697, 555, 630, 990, 920, 988, 820, 833, 836, 1066, 646, 1222, 975, 1363, 1118, 1815, 1750, 1431, 858, 1320, 1029, 1175, 1100, 1008, 1248, 1372, 1705, 1457, 1550, 1581, 1581, 1426, 1056, 1029, 1325, 1200, 920, 1222, 960, 616, 900, 672, 688, 510, 741, 1025, 1008, 980, 918, 848, 608, 676, 752, 675, 882, 1275, 1225, 882, 752, 990, 576, 756, 860, 546, 945, 720, 656, 1196, 703, 702, 624, 624, 630, 1350, 1200, 1150, 1350, 1425, 697, 544, 817, 720, 1012, 592, 656, 833, 290, 646, 880, 799, 1296, 1008, 1296, 1224, 1008, 819, 726, 756, 544, 1170, 1040, 1272, 880, 968, 880, 1325, 646, 1250, 1175, 817, 741, 1428, 720, 840, 1040, 984, 880, 966, 1484, 1568, 912, 836, 1078, 960, 798, 900, 1320, 588, 720, 608, 1078, 756, 434, 1080, 816, 1056, 1196, 910, 1196, 1274, 434, 1118, 574, 442, 672, 1265, 1357, 1426, 1288, 1495, 675, 720, 784, 444, 1152, 780, 1170, 945, 1080, 570, 920, 702, 532, 1000, 1350, 1276, 960, 940, 406, 550, 648, 416, 1000, 990, 774, 406, 392, 705, 756, 1000, 760, 752, 748, 893, 1025, 966, 954, 1210, 455, 1007, 408, 1081, 1566, 836, 624, 1150, 918, 800, 1431, 1050, 1040, 874, 624, 1220, 819, 533, 984, 1403, 945, 640, 630, 1060, 1020, 924, 912, 444, 1200, 738, 969, 798, 1102, 1008, 760, 1155, 1071, 624, 1242, 1152, 1125, 990, 980, 1176, 756, 658, 850, 640, 780, 525, 943, 688, 705, 1056, 980, 624, 855, 532, 800, 1144, 990, 800, 1176, 615, 1012, 950, 646, 836, 861, 456, 578, 697, 507, 429, 1220, 731, 720, 540, 572, 704, 968, 768, 672, 736, 680, 598, 774, 817, 720, 779, 672, 864, 735, 481, 840, 1150, 510, 1012, 688, 612, 576, 840, 1152, 1050, 1000, 1250, 600, 1150, 1200, 860, 1972, 1173, 1210, 968, 819, 1170, 1104, 1056, 980, 984, 1150, 1222, 1176, 920, 1269, 1222, 1120, 1161, 1150, 1092, 756, 1196, 1248, 1248, 1122, 1197, 880, 1080, 1352, 1040, 1566, 968, 1222, 760, 1037, 1066, 245, 1296, 1296, 966, 1032, 1144, 384, 738, 684, 1296, 820, 989, 630, 988, 1150, 1248, 900, 1215, 720, 1274, 882, 1128, 665, 1152, 1050, 528, 1092, 1150, 714, 760, 1224, 1450, 987, 756, 1100, 1323, 990, 1050, 1175, 1056, 1219, 516, 1288, 864, 450, 966, 944, 627, 450, 517, 989, 432, 1128, 740, 714, 990, 860, 731, 1012, 629, 990, 1222, 833, 774, 1000, 867, 570, 1170, 798, 1035, 1290, 1078, 1176, 814, 1152, 900, 946, 814, 697, 924, 988, 1333, 714, 1056, 1176, 1250, 893, 893, 1320, 893, 1512, 798, 779, 874, 940, 1173, 1050, 1056, 748, 1378, 1150, 931, 1083, 1012, 1176, 990, 1078, 1127, 1166, 1144, 966, 1000, 1150, 1150, 1488, 741, 1275, 1035, 1196, 688, 760, 1222, 840, 874, 1127, 1127, 858, 777, 855, 756, 1035, 494, 740, 1127, 1144, 1890, 594, 850, 1176, 656, 680, 840, 630, 1430, 1590, 702, 1325, 1175, 1056, 1595, 1104, 1035, 1056, 858, 882, 480, 1034, 810, 968, 594, 792, 1012, 800, 987, 1056, 1056, 1219, 1080, 782, 774, 1122, 1408, 570, 1012, 1378, 1134, 924, 1275, 1274, 882, 1450, 1166, 1247, 1568, 1247, 760, 720, 893, 779, 1175, 660, 1045, 684, 544, 760, 697, 1188, 1175, 836, 968, 1056, 1457, 1056, 1440, 1175, 840, 798, 774, 1404, 931, 1323, 960, 1008, 490, 1104, 1092, 1458, 1344, 924, 1368, 1104, 1066, 968, 846, 1144, 680, 1275, 1305, 980, 880, 1242, 1372, 1200, 1265, 966, 1404, 989, 1176, 1144, 833, 1342, 1150, 1416, 902, 1215, 1188, 1035, 943, 1215, 980, 1219, 1316, 1104, 1100, 1050, 910, 882, 1008, 987, 1012, 1034, 840, 1058, 1219, 1150, 924, 1150, 722, 836, 1104, 1175, 912, 1456, 1288, 1274, 1222, 1222, 798, 1144, 1248, 1080, 1372, 1485, 900, 903, 1200, 756, 1150, 1081, 988, 900, 968, 920, 1020, 1125, 1300, 920, 825, 1100, 988, 1050, 1140, 1247, 1092, 1071, 903, 912, 1200, 1300, 1400, 975, 1029, 480, 828, 836, 1485, 1218, 1248, 1272, 1470, 736, 1380, 1431, 840, 1219, 1050, 1500, 1215, 855, 1000, 1170, 945, 646, 903, 968, 1368, 1128, 1161, 1222, 945, 1081, 1134, 940, 1296, 1428, 1232, 736, 984, 903, 1081, 1800, 2016, 1416, 1908, 1908, 714, 574, 1175, 1305, 1104, 1104, 1431, 1421, 1479, 920, 1104, 1175, 1537, 798, 468, 624, 1421, 968, 630, 1173, 1125, 2016, 1250, 1352, 1080, 1431, 1224, 1248, 1176, 1173, 880, 1484, 1485, 1440, 1215, 880, 940, 1242, 1152, 1372, 1176, 800, 722, 1750, 1564, 1232, 1200, 1176, 1107, 1200, 1456, 1316, 1144, 1269, 1479, 1215, 1368, 1012, 1440, 1122, 1204, 1008, 1326, 1200, 960, 1380, 1104, 1040, 1326, 1350, 1595, 1152, 1056, 1144, 1144, 1272, 960, 1128, 1034, 1128, 1176, 1770, 1166, 1320, 1066, 1222, 1224, 1080, 920, 1323, 816, 1075, 1122, 1222, 1012, 832, 1144, 1066, 1056, 1323, 1368, 1566, 1176, 1566, 1404, 1430, 1512, 1537, 984, 1525, 984, 1152, 1250, 1500, 1410, 1400, 1152, 1100, 1375, 1150, 1125, 1125, 1050, 1242, 1175, 1200, 1250, 1075, 1323, 1323, 1392, 1247, 1247, 800, 1508, 984, 1040, 1380, 864, 1104, 1248, 960, 1380, 1296, 1050, 924, 1176, 836, 1092, 1392, 1196, 1323, 1196, 1479, 1128, 1539, 780, 1265, 1512, 1431, 1392, 1392, 1537, 780, 1144, 1274, 1125, 1392, 700, 1350, 1248, 640, 1269, 1100, 820, 945, 1372, 1352, 780, 946, 920, 989, 1066, 1860, 1012, 1012, 1550, 1104, 1767, 1488, 960, 1092, 1767, 1056, 952, 1320, 1584, 1372, 1485, 1323, 1456, 1372, 1064, 1428, 1222, 1848, 1596, 1320, 1230, 1056, 1305, 1334, 1012, 864, 1305, 946, 1350, 1204, 1034, 1025, 1325, 1040, 1104, 703, 1856, 984, 828, 1248, 1092, 836, 722, 814, 805, 1080, 1404, 819, 902, 1568, 1008, 1100, 1440, 946, 989, 1152, 1104, 1012, 1440, 1664, 902, 1792, 1612, 1188, 1728, 920, 966, 1058, 1458, 920, 798, 828, 1550, 1537, 966, 1040, 946, 1296, 1458, 1395, 966, 990, 630, 1296, 1161, 1458, 1118, 1428, 1170, 1593, 748, 924, 1050, 1428, 1428, 987, 880, 1512, 861, 850, 1430, 741, 665, 779, 697, 646, 1032, 1269, 1053, 1300, 1274, 912, 722, 1008, 1404, 1050, 1071, 1100, 968, 1344, 760, 697, 840, 936, 1404, 1100, 1075, 612, 980, 984, 1276, 1144, 1296, 1056, 760, 1222, 1617, 987, 1050, 1269, 903, 555, 945, 817, 600, 624, 544, 1333, 1078, 1035, 770, 1344, 1296, 741, 1012, 703, 1215, 897, 770, 1188, 510, 1152, 665, 1421, 858, 370, 720, 1350, 882, 1248, 1316, 1224, 814, 735, 779, 525, 840, 1323, 1400, 1080, 968, 840, 931, 902, 968, 1034, 720, 1323, 1056, 420, 836, 1071, 798, 882, 855, 495, 1323, 1118, 1512, 1050, 760, 1170, 798, 1176, 1274, 846, 1242, 1215, 864, 1032, 1372, 544, 1218, 1400, 644, 840, 532, 1064, 840, 858, 420, 924, 1134, 420, 1265, 1104, 1144, 1440, 1104, 1334, 1104, 1196, 1215, 880, 946, 1248, 1034, 656, 1196, 672, 1050, 646, 385, 532, 392, 1300, 1600, 1620, 1250, 1204, 903, 1071, 1440, 1375, 874, 817, 1225, 1380, 1728, 1071, 1035, 1225, 1012, 1375, 608, 722, 740, 1092, 810, 1058, 1512, 798, 920, 777, 756, 1350, 840, 752, 1300, 1484, 572, 756, 1550, 1066, 507, 1176, 738, 1275, 968, 1440, 756, 1428, 851, 1275, 1200, 1450, 589, 900, 946, 1500, 861, 684, 1620, 1566, 1350, 544, 940, 756, 544, 798, 820, 1400, 720, 920, 1652, 1344, 1600, 1066, 1378, 1428, 1204, 1540, 396, 1708, 800, 1014, 1050, 465, 693, 1600, 1325, 1456, 665, 861, 684, 800, 496, 555, 1100, 1326, 752, 703, 748, 765, 1060, 540, 722, 1060, 1425, 860, 836, 1224, 1431, 1674, 1113, 880, 945, 966, 855, 1269, 1104, 1222, 1173, 1357, 1035, 980, 1755, 1000, 780, 836, 1539, 840, 640, 850, 1034, 703, 684, 196, 396, 966, 720, 893, 924, 1120, 968, 924, 902, 858, 874, 779, 760, 798, 855, 903, 1050, 1034, 1479, 1296, 1368, 1200, 1612, 1128, 1100, 1188, 1404, 1632, 840, 680, 1485, 1377, 1508, 1161, 1269, 1323, 740, 720, 1008, 656, 456, 640, 1232, 840, 330, 1416, 1674, 1248, 1242, 1326, 1674, 1320, 1352, 1104, 1056, 1128, 1798, 1767, 1200, 1071, 966, 903, 987, 820, 760, 1456, 1586, 840, 1352, 1107, 980, 1248, 1104, 1215, 988, 780, 1248, 780, 920, 680, 940, 1008, 680, 1410, 1508, 560, 490, 1530, 1363, 1479, 490, 840, 819, 924, 903, 1300, 676, 1551, 1404, 1392, 1568, 1508, 1276, 1566, 1652, 1472, 1792, 1392, 1664, 1431, 434, 1352, 902, 990, 1071, 1344, 1075, 792, 1624, 987, 1148, 1296, 1092, 1050, 1334, 1100, 1316, 1728, 1377, 903, 504, 1377, 637, 1176, 814, 989, 940, 940, 680, 1000, 741, 741, 798, 779, 648, 646, 774, 765, 1540, 820, 1333, 574, 954, 816, 990, 560, 1140, 988, 836, 855, 1204, 703, 1080, 731, 592, 372, 714, 1053, 860, 576, 760, 1000, 351, 731, 312, 740, 1020, 1020, 960, 880, 1144, 1140, 580, 882, 946, 946, 836, 1035, 874, 893, 1032, 1161, 756, 943, 828, 820, 946, 920, 1188, 722, 861, 828, 1242, 684, 697, 779, 1144, 1035, 1104, 989, 851, 1012, 615, 1196, 570, 1100, 1484, 920, 589, 984, 1428, 1066, 646, 820, 960, 1652, 1060, 1428, 1080, 1104, 612, 988, 741, 920, 980, 940, 1078, 980, 645, 960, 1512, 1300, 1140, 960, 990, 1026, 950, 980, 810, 1534, 600, 969, 924, 931, 645, 174, 1140, 1020, 860, 1020, 675, 630, 1040, 330, 532, 1269, 1320, 920, 1400, 495, 900, 1200, 540, 592, 756, 954, 1128, 1071, 451, 1475, 1128, 888, 1450, 966, 828, 1104, 666, 1425, 1056, 1104, 1200, 1144, 1400, 836, 1224, 990, 1458, 1248, 1113, 1104, 1144, 1344, 570, 1075, 510, 1300, 1250, 1450, 882, 1248, 900, 882, 1196, 663, 912, 585, 880, 1188, 1458, 1595, 864, 1334, 1323, 1150, 1740, 1107, 780, 1404, 1653, 1363, 1215, 1363, 820, 1144, 1188, 1350, 1323, 1150, 969, 1320, 1922, 1159, 600, 1100, 1000, 1215, 1034, 798, 903, 175, 1210, 774, 252, 1298, 880, 703, 817, 224, 1296, 216, 990, 969, 1176, 833, 540, 935, 980, 954, 1078, 1127, 592, 840, 984, 952, 525, 1225, 646, 1275, 1357, 736, 1311, 903, 627, 1150, 646, 810, 760, 1242, 1767, 946, 736, 1458, 680, 1050, 1274, 1128, 448, 684, 760, 1104, 1276, 600, 798, 1034, 1404, 816, 798, 799, 903, 736, 680, 969, 920, 600, 840, 684, 1060, 1170, 1450, 1200, 276, 1456, 984, 966, 1364, 1539, 1350, 1056, 1323, 1537, 780, 1320, 1104, 243, 1271, 1392, 1736, 1595, 1104, 1352, 903, 984, 1518, 1056, 1400, 1450, 1400, 256, 1590, 1012, 1740, 1250, 735, 341, 714, 1104, 1161, 1296, 1782, 1612, 1728, 1664, 840, 1952, 1204, 1568, 527, 1568, 1824, 1600, 1196, 1352, 1260, 1421, 1643, 1736, 1410, 1650, 1536, 561, 1612, 1320, 1426, 1512, 1705, 1770, 544, 1540, 1650, 1519, 275, 882, 1188, 1650, 774, 312, 216, 810, 931, 272, 980, 1050, 893, 882, 1071, 175, 1140, 966, 833, 1508, 779, 1040, 1092, 576, 893, 210, 1269, 950, 784, 1104, 836, 741, 858, 1092, 836, 924, 1056, 210, 735, 840, 1176, 600, 799, 374, 800, 720, 882, 1508, 1176, 1344, 1260, 1512, 1375, 1372, 1125, 1344, 420, 741, 1232, 987, 731, 828, 1008, 846, 374, 1029, 940, 1029, 874, 396, 900, 912, 810, 988, 874, 945, 931, 817, 560, 950, 1372, 903, 920, 1008, 1150, 864, 756, 492, 864, 864, 360, 1020, 1400, 950, 846, 1150, 493, 544, 646, 646, 504, 1350, 972, 736, 986, 1225, 629, 720, 592, 1711, 850, 969, 714, 595, 816, 1311, 780, 1242, 935, 510, 697, 1595, 1334, 688, 656, 714, 396, 846, 855, 680, 646, 714, 1196, 855, 656, 720, 1081, 1537, 1479, 1250, 1127, 882, 1104, 855, 1058, 690, 1200, 1479, 1225, 882, 748, 525, 936, 954, 972, 782, 688, 656, 1302, 1272, 1550, 954, 396, 624, 777, 510, 954, 900, 672, 1224, 1426, 850, 612, 704, 820, 1416, 882, 1392, 544, 954, 1416, 750, 735, 645, 874, 820, 578, 675, 560, 312, 663, 765, 900, 855, 850, 833, 936, 630, 940, 901, 350, 1121, 1081, 1155, 840, 1197, 1239, 688, 1029, 1081, 1134, 518, 800, 1364, 1104, 1128, 1078, 1034, 820, 456, 860, 1200, 506, 451, 1272, 980, 1081, 1152, 1276, 1210, 1034, 752, 1100, 684, 1166, 1272, 936, 1296, 684, 468, 2278, 600, 518, 360, 1269, 1248, 1122, 924, 1056, 1104, 1012, 952, 893, 507, 884, 481, 175, 624, 2312, 688, 946, 297, 1375, 1080, 960, 952, 760, 576, 1224, 1050, 1225, 1222, 1325, 946, 1071, 784, 798, 1316, 1075, 1170, 903, 663, 1525, 798, 968, 874, 960, 833, 782, 902, 640, 1344, 702, 1176, 1222, 351, 646, 672, 1104, 774, 1363, 1265, 672, 924, 1218, 1300, 336, 990, 1029, 1316, 341, 1176, 600, 960, 1344, 1060, 1125, 900, 1248, 646, 1173, 560, 1026, 1026, 988, 200, 1150, 1066, 950, 598, 765, 1325, 931, 936, 741, 572, 882, 592, 520, 1150, 1300, 988, 1100, 330, 874, 903, 988, 690, 1274, 816, 864, 1050, 602, 1276, 990, 1326, 1066, 924, 208, 1377, 1000, 1342, 968, 1377, 936, 902, 1680, 1056, 861, 420, 1620, 363, 1767, 1470, 1000, 416, 1457, 1650, 1560, 1311, 945, 1210, 903, 1173, 576, 1674, 1643, 1104, 630, 968, 1705, 1127, 1050, 1392, 1326, 1404, 943, 693, 1173, 792, 468, 648, 924, 987, 819, 988, 1250, 693, 882, 893, 338, 946, 1144, 416, 735, 880, 1050, 782, 480, 903, 1152, 1092, 861, 1350, 646, 1200, 1150, 592, 1092, 1242, 756, 1380, 629, 1066, 1219, 903, 540, 1012, 1404, 527, 1456, 1107, 1125, 1008, 1127, 1066, 1080, 1034, 561, 855, 1378, 448, 774, 1352, 722, 1275, 1316, 1288, 500, 1274, 735, 1375, 722, 777, 858, 990, 1404, 1170, 1325, 1560, 1056, 1512, 1032, 585, 902, 946, 1400, 1512, 432, 1176, 1080, 1188, 1350, 1404, 1035, 840, 777, 1012, 943, 1377, 1080, 1034, 540, 1431, 1272, 1197, 1512, 1316, 1242, 1620, 1104, 902, 1485, 1540, 1053, 1188, 924, 516, 1012, 330, 1200, 1508, 810, 1372, 220, 984, 968, 1488, 253, 990, 1710, 1144, 946, 576, 1058, 1210, 1032, 1372, 820, 1320, 966, 1344, 1530, 1664, 1800, 1560, 920, 1120, 1035, 1416, 189, 920, 1344, 1200, 510, 1320, 1392, 1056, 800, 680, 646, 1560, 1008, 1452, 1071, 740, 560, 1260, 800, 1080, 1152, 897, 1056, 275, 1540, 1078, 1161, 1296, 615, 1225, 1014, 624, 825, 598, 1150, 966, 620, 465, 840, 966, 396, 880, 495, 658, 735, 1150, 1175, 1175, 765, 630, 546, 615, 893, 585, 851, 518, 720, 1078, 714, 1029, 1150, 1058, 832, 752, 1008, 1127, 784, 1426, 731, 1296, 528, 1058, 629, 897, 714, 765, 574, 640, 861, 1122, 1008, 1150, 500, 799, 726, 984, 702, 828, 728, 765, 555, 946, 741, 900, 752, 490, 612, 640, 720, 720, 1012, 720, 518, 1125, 1075, 1200, 1012, 646, 1734, 779, 1050, 1848, 1323, 1166, 1617, 943, 1749, 858, 684, 600, 1104, 1045, 561, 266, 836, 310, 672, 1296, 630, 1150, 968, 936, 629, 980, 1104, 990, 936, 779, 612, 1008, 1050, 1363, 1450, 532, 1008, 444, 1107, 1479, 684, 1092, 1802, 840, 1155, 784, 1700, 688, 1029, 1457, 1457, 1581, 1488, 1080, 688, 968, 1564, 736, 780, 820, 920, 940, 1166, 1333, 1666, 792, 702, 1617, 1584, 1026, 1150, 792, 645, 261, 560, 882, 1265, 986, 684, 901, 1044, 690, 1173, 1242, 384, 1104, 555, 722, 1026, 1000, 1040, 1134, 850, 1000, 954, 861, 840, 1248, 1296, 988, 784, 1160, 1008, 900, 520, 1080, 1116, 370, 880, 780, 867, 1044, 832, 400, 1125, 885, 644, 816, 672, 1092, 795, 969, 352, 1425, 688, 1056, 846, 1320, 555, 1464, 782, 968, 714, 946, 507, 1250, 1092, 1224, 1166, 1122, 2040, 2142, 943, 484, 855, 817, 1007, 1007, 900, 196, 840, 1500, 1056, 966, 432, 612, 1300, 594, 988, 1290, 960, 969, 765, 630, 1296, 779, 817, 950, 722, 720, 675, 1128, 832, 1020, 145, 750, 1008, 1938, 1296, 980, 2006, 624, 592, 2142, 672, 185, 2346, 960, 1242, 448, 1173, 1539, 1058, 1176, 1104, 1485, 1566, 1196, 752, 1470, 920, 624, 880, 752, 1081, 1593, 2294, 2077, 2170, 561, 578, 2232, 684, 612, 756, 810, 1596, 2263, 1820, 1144, 1352, 3311, 858, 1404, 1404, 1377, 1431, 1566, 3483, 1118, 1378, 1196, 1274, 1482, 3354, 2394, 1581, 3483, 2356, 2394, 3096, 2660, 2242, 1620, 1590, 1770, 1950, 1920]

In [12]:
sum(chunks)

5268958

In [ ]:
len(df['inv_distance'].iloc[0])

In [10]:
df['inv_distance'].iloc[0].reshape(-1,df[''])

array([0.08074464, 0.08486807, 0.10579175, 0.14943988, 0.10081385,
       0.07986411, 0.06986314, 0.06019579, 0.05168361, 0.05755385,
       0.04791004, 0.06248953, 0.07388024, 0.09677104, 0.09384255,
       0.1071482 , 0.16690572, 0.09066126, 0.07578793, 0.06445164,
       0.05773727, 0.04853275, 0.05819043, 0.04922451, 0.06581658,
       0.07661704, 0.09735222, 0.09389486, 0.1057804 , 0.1588679 ,
       0.08943599, 0.07544679, 0.0642202 , 0.05776214, 0.04853579,
       0.05843301, 0.04954233, 0.06619403, 0.07675342, 0.09129987,
       0.09274563, 0.10993093, 0.15521718, 0.09819059, 0.08066254,
       0.06931662, 0.06106537, 0.0516103 , 0.06013522, 0.05033087,
       0.06677312, 0.07839668, 0.09899671, 0.10532984, 0.13563098,
       0.19612796, 0.12507746, 0.096281  , 0.08153348, 0.06945816,
       0.05796435, 0.06677436, 0.05441785, 0.07374149, 0.08934204,
       0.09316187, 0.10378579, 0.14141225, 0.1778728 , 0.14747756,
       0.10692416, 0.0921269 , 0.0754913 , 0.06343512, 0.06976

In [35]:
df[df['smiles'].str.contains("I")]

smiles  \
66284  [H:11][c:1]1[c:2]([c:3]([c:4]([c:6]([c:10]1[H:...   
66289  [H:11][c:1]1[c:2]([c:3]([c:4]([c:6]([c:10]1[H:...   

                                                  dipole  \
66284  [0.015187710480546457, 0.3128338265104844, 0.3...   
66289  [0.40494203737050327, 0.7872244132345827, 1.10...   

                                            conformation  \
66284  [1.3180059, 2.27671906, 0.26514125, 0.64367486...   
66289  [1.15817381, 2.40462837, 0.31200235, 0.6568114...   

                                            mbis-charges  \
66284  [-0.17085972418007112, -0.09652039571444607, -...   
66289  [-0.15352911682308495, -0.10555315461039355, -...   

                                            mbis-dipoles  \
66284  [-0.010340751945866793, -0.024800926635769542,...   
66289  [-0.007995841172668718, -0.028921229005029418,...   

                                        mbis-quadrupoles  \
66284  [-4.470149345069374, -0.06407696846483699, -0....   
66289  [-4.434488176595943, -0.05394198823598003, -0....   

                                            inv_distance  \
66284  [0.06725316795822858, 0.07185346466807481, 0.0...   
66289  [0.06806136740876834, 0.072729529232634, 0.088...   

                                                     esp  record_id  \
66284  [0.0024516047516192872, -0.0001402557424234711...  138022083   
66289  [-0.0016944581166743766, -0.00909278112909524,...  138021942   

       esp_length                                               grid  
66284          50  [-8.52919616070973, -8.69302434883473, -1.6816...  
66289          54  [-8.43792526195973, -8.56687584445973, -1.5357...

In [18]:
entry_num = 3
df.iloc[entry_num]['smiles']

'[H:12][C:1]1([C:3]2([C:2]1([C:6]([C:5]3([C:4]2([H:16])[H:17])[C:7]([N+:8]([C:9]([C:10]3([H:26])[N:11]([H:27])[H:28])([H:24])[H:25])([H:22])[H:23])([H:20])[H:21])([H:18])[H:19])[H:14])[H:15])[H:13]'

In [19]:
charges = df.iloc[entry_num]['mbis-charges']
charges

array([-0.30014314, -0.15122066, -0.12910858, -0.19618956, -0.0812495 ,
       -0.18896042, -0.07290186, -0.41174119, -0.11587172,  0.14190943,
       -0.83589359,  0.17418876,  0.15373945,  0.14647495,  0.14701923,
        0.12840077,  0.12298923,  0.09724971,  0.1212515 ,  0.13987028,
        0.15921886,  0.39507397,  0.39038863,  0.15829533,  0.15264715,
        0.11900745,  0.35993365,  0.37541609])

In [20]:
inv_distance = df.iloc[entry_num]['inv_distance']
(inv_distance * unit.angstrom).to(unit.bohr)
np.around(inv_distance, decimals=3)

array([0.111, 0.099, 0.129, ..., 0.101, 0.104, 0.085])

In [21]:
esp = df.iloc[entry_num]['esp']
esp

array([0.097386  , 0.09066618, 0.07830007, 0.08339948, 0.11493734,
       0.0874154 , 0.1246588 , 0.08722247, 0.08533495, 0.11012078,
       0.09826675, 0.08448454, 0.13298073, 0.08551254, 0.08165641,
       0.1224535 , 0.13730349, 0.11743218, 0.15203713, 0.10528679,
       0.12567374, 0.08663638, 0.0883598 , 0.1499988 , 0.1334413 ,
       0.13605809, 0.10491766, 0.08826848, 0.13129912, 0.09726355,
       0.15328749, 0.1779227 , 0.13568867, 0.12430328, 0.13455812,
       0.16543964, 0.11203783, 0.09522439, 0.11786269, 0.1585529 ,
       0.17773719, 0.14480266, 0.17055247])

In [22]:
np.around(esp, decimals=3)

array([0.097, 0.091, 0.078, 0.083, 0.115, 0.087, 0.125, 0.087, 0.085,
       0.11 , 0.098, 0.084, 0.133, 0.086, 0.082, 0.122, 0.137, 0.117,
       0.152, 0.105, 0.126, 0.087, 0.088, 0.15 , 0.133, 0.136, 0.105,
       0.088, 0.131, 0.097, 0.153, 0.178, 0.136, 0.124, 0.135, 0.165,
       0.112, 0.095, 0.118, 0.159, 0.178, 0.145, 0.171])

In [23]:
np.around(charges, decimals=3)

array([-0.3  , -0.151, -0.129, -0.196, -0.081, -0.189, -0.073, -0.412,
       -0.116,  0.142, -0.836,  0.174,  0.154,  0.146,  0.147,  0.128,
        0.123,  0.097,  0.121,  0.14 ,  0.159,  0.395,  0.39 ,  0.158,
        0.153,  0.119,  0.36 ,  0.375])

In [24]:
df.iloc[1]['conformation'].reshape(-1,3)

array([[-0.20376959, -0.11846028, -1.65358243],
       [-1.59402315,  2.13690171, -1.05129905],
       [-2.75552036,  3.53325196, -2.4443893 ],
       [-1.43800521,  2.5738108 ,  1.56284316],
       [-0.15386633,  1.07352862,  3.27199497],
       [ 1.08339838, -0.94858474,  2.67782792],
       [ 1.02611106, -1.50802107,  0.16730485],
       [ 2.16242222, -3.5204282 , -0.98175933],
       [ 1.6778943 , -3.40531446, -3.37928799],
       [ 0.25842054, -1.37766896, -3.83353998],
       [-0.23310587,  1.82394778,  5.7226748 ],
       [-2.3622033 ,  4.12515406,  2.16489191],
       [-0.3095622 , -0.97335439, -5.59717816],
       [ 0.68797699,  0.7571835 ,  6.98700592],
       [-1.15523632,  3.36550031,  6.30376892]])

In [25]:

client = PortalClient("api.qcarchive.molssi.org", cache_dir=".")

data_set = client.get_dataset(dataset_type='singlepoint',dataset_name='MLPepper RECAP Optimized Fragments v1.0')
entries = data_set.entry_names


In [26]:
iterate = data_set.iterate_records(specification_names=["wb97x-d/def2-tzvpp/ddx-water"], status="complete", entry_names=entries[10])

In [27]:
molecule = Molecule.from_qcschema(next(iterate)[-1].molecule, allow_undefined_stereo=True)
molecule.conformers[0].m

array([[-2.93162698, -1.26827556, -0.17203114],
       [-3.72417461, -0.11698123, -0.27981249],
       [-3.17604605,  1.08767791, -0.28752058],
       [-1.86623491,  1.11231275, -0.18862111],
       [-1.08417069, -0.06361528, -0.08062715],
       [-1.61958189, -1.26853964, -0.07193782],
       [ 0.62748374,  0.02612671,  0.04624832],
       [-1.11358662,  2.66068207, -0.19485726],
       [-5.06298164, -0.45854589, -0.36789528],
       [-5.05743054, -1.74992253, -0.31438783],
       [-3.8146962 , -2.32264969, -0.19605329],
       [-6.4483831 , -2.73165085, -0.38013209],
       [-3.60459439, -3.30255485, -0.1397228 ]])

In [28]:
molecule = Molecule.from_mapped_smiles(df.iloc[1]['smiles'])
molecule.add_conformer(df.iloc[1]['conformation'].reshape(-1,3)* unit.angstrom)
molecule.to_smiles()

'[H][N]([H])[C]1=[N][C]2=[C]([C](=[O])[N]1[H])[N]([H])[N]=[N]2'

In [29]:
molecule.conformers[0].m

array([[-0.20376959, -0.11846028, -1.65358243],
       [-1.59402315,  2.13690171, -1.05129905],
       [-2.75552036,  3.53325196, -2.4443893 ],
       [-1.43800521,  2.5738108 ,  1.56284316],
       [-0.15386633,  1.07352862,  3.27199497],
       [ 1.08339838, -0.94858474,  2.67782792],
       [ 1.02611106, -1.50802107,  0.16730485],
       [ 2.16242222, -3.5204282 , -0.98175933],
       [ 1.6778943 , -3.40531446, -3.37928799],
       [ 0.25842054, -1.37766896, -3.83353998],
       [-0.23310587,  1.82394778,  5.7226748 ],
       [-2.3622033 ,  4.12515406,  2.16489191],
       [-0.3095622 , -0.97335439, -5.59717816],
       [ 0.68797699,  0.7571835 ,  6.98700592],
       [-1.15523632,  3.36550031,  6.30376892]])

In [30]:
df_2 =  pd.read_parquet("mlpepper_water_esp.parquet")
df_2

smiles  \
0      [H:15][C:3]1([C:2]2([C:1]([N+:8]([C:7]([C:6]2(...   
1      [H:12][c:1]1[c:2]2[c:3]([n:4][c:5]([n:6]1)[H:1...   
2      [H:12][C:1]1([C:8]([N:7]([C:3]2([C:2]1([C:4]2(...   
3      [H:11][C:1]1([C:2]([C:3]12[C:4]([C:5]([C:6]2([...   
4      [H:12][C:1]1([C:2]2([C:3]([C:4]([S:5]1(=[O:6])...   
...                                                  ...   
68961  [H:19][C:1](=[O:2])[C@@:3]1([C@:12]([C@@:11]2(...   
68962  [H:19][C:1](=[O:2])[C@@:3]1([C@:12]([C@@:11]2(...   
68963  [H:19][C:1](=[O:2])[C@:3]1([C@:12]([C@@:11]2([...   
68964  [H:21][C:1](=[O:2])[C@:3]1([C@:14]([C@:13]2([C...   
68965  [H:19][C:1](=[O:2])[C@:3]1([C@:12]([C@:11]2([C...   

                                                  dipole  \
0      [-0.7258902700808072, -0.21672904754614564, 0....   
1      [5.445917765483706, -1.0675844401459944, 0.657...   
2      [-0.6895126220985865, -2.3897443402088303, -5....   
3      [-2.6701464398881996, -1.9285174681081187, -8....   
4      [-0.38386947268983995, 0.39288500866755705, 0....   
...                                                  ...   
68961  [-2.2726171827263784, -0.6836081014171889, 0.2...   
68962  [1.9077593614395028, 1.3643698574887821, 0.930...   
68963  [-1.3860567729865352, -0.7124856283247425, -1....   
68964  [-0.26798684356820957, -2.2810406409886355, -1...   
68965  [0.5985387176132271, -0.4367963966209061, 1.17...   

                                            conformation  \
0      [-2.170121, -2.094219, 1.91176183, -1.52670825...   
1      [-0.22226432, 1.0797565, 3.17284233, 0.3847130...   
2      [-2.43517885, 0.49960588, 1.24271947, -1.74276...   
3      [-1.98783721, 1.26210552, -3.32277385, -1.9109...   
4      [-0.99956575, 2.52827571, 1.58963491, -0.75523...   
...                                                  ...   
68961  [1.8841439, 4.84971322, -2.06462836, 3.3336158...   
68962  [-2.76850699, -3.85617022, -2.55506677, -4.371...   
68963  [-2.14753944, 5.50810402, -0.37719514, -1.9370...   
68964  [-1.42272088, -3.50620732, 4.71830642, -1.7691...   
68965  [4.99592445, -2.06497372, 1.42482755, 7.062196...   

                                            mbis-charges  \
0      [-0.06715269608532415, -0.06219141445770018, -...   
1      [0.24241876921135544, -0.2690989482898696, 0.4...   
2      [-0.18379686831191241, -0.29660615512665656, -...   
3      [-0.3486362168253557, -0.36597168569857785, 0....   
4      [-0.5401716249008178, 0.17452389078740044, -0....   
...                                                  ...   
68961  [0.3996099181522406, -0.5090550804618816, 0.17...   
68962  [0.42088857174227373, -0.5217455884582598, 0.1...   
68963  [0.4134410514448352, -0.5106582555970944, 0.13...   
68964  [0.3929265648445292, -0.49871888294747607, 0.1...   
68965  [0.4026944851598294, -0.5097110813526565, 0.13...   

                                            mbis-dipoles  \
0      [0.10144954697255087, -0.0030391528826854623, ...   
1      [-0.09013881069329062, 0.047634456719904406, 0...   
2      [0.05196544417763481, -0.05007694231193955, -0...   
3      [0.008187482945214283, -0.04240839967514316, 0...   
4      [0.000989562445684087, 0.05754229447578587, -0...   
...                                                  ...   
68961  [0.05813912492151028, 0.07392852201174697, -0....   
68962  [-0.07037606694875999, -0.043478670696657555, ...   
68963  [0.0011520899810302124, 0.08555443039354375, -...   
68964  [-0.001883323171639251, 0.0649046498014438, 0....   
68965  [0.0903058827763588, 0.03590355742742697, -0.0...   

                                        mbis-quadrupoles  \
0      [-4.227355375402022, -0.06958129963578065, 0.0...   
1      [-3.85476200480249, 0.1041279159774863, -0.020...   
2      [-4.591170654015003, 0.05035498632619183, 0.00...   
3      [-4.90282474368359, 0.02742360172488209, -0.04...   
4      [-5.1482484935297075, 0.0011647278749044084, 0...   
...                                                  ...   
68961  [-3.68663620742905

In [31]:
df_2.iloc[1]

smiles              [H:12][c:1]1[c:2]2[c:3]([n:4][c:5]([n:6]1)[H:1...
dipole              [5.445917765483706, -1.0675844401459944, 0.657...
conformation        [-0.22226432, 1.0797565, 3.17284233, 0.3847130...
mbis-charges        [0.24241876921135544, -0.2690989482898696, 0.4...
mbis-dipoles        [-0.09013881069329062, 0.047634456719904406, 0...
mbis-quadrupoles    [-3.85476200480249, 0.1041279159774863, -0.020...
inv_distance        [0.09803106453439497, 0.09589364352215221, 0.1...
esp                 [0.059278792227986515, 0.0655529841634353, 0.0...
record_id                                                   138025318
esp_length                                                         47
Name: 1, dtype: object

In [32]:
 df_2[df_2['smiles'] == '[H:11][C:1]1([C:6]2([C:5]([C:4]3([C:3]([C:2]1([C:9]([C:8]([C:7]2([H:20])[H:21])([C:10]3([H:25])[H:26])[H:22])([H:23])[H:24])[H:13])([H:14])[H:15])[H:16])([H:17])[H:18])[H:19])[H:12]']['mbis-charges'].item()

array([-0.25307059, -0.02675983, -0.2530846 , -0.02643505, -0.25316385,
       -0.02641427, -0.25306785, -0.02664462, -0.25322968, -0.25308723,
        0.10461939,  0.10641578,  0.09011208,  0.10536142,  0.10526495,
        0.090709  ,  0.10500955,  0.10539747,  0.08992717,  0.10596022,
        0.10486828,  0.08985918,  0.10478978,  0.10631435,  0.10530606,
        0.10531575])